/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Processor.conversion;
import Processor.imageProcessor;
import constants.imageConfiguration;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class main_view extends javax.swing.JPanel {
    //usage variables
    private conversion imageConv = new conversion();
    private String path_string=  "C:/Users/Andy/Desktop/Portfolio resources/view1.jpg";
    public File images_path = new File(path_string);
    public BufferedImage image;
    imageProcessor ip = new imageProcessor();
    //setting variables
    int conv_size_set = 3;
    int conv_method_set = imageConfiguration._AVERAGE;
    int conv_paddOpt_set = imageConfiguration._BLACK;
    boolean rgb_enabled = false;
    //option variables
    public int[] conv_size_int = new int[]{3, 5, 7, 9, 11};
    public String[] conv_size_string = new String[]{"3 x 3", "5 x 5", "7 x 7", "9 x 9", "11 x 11" };
    public int[] conv_method_int = new int[] {imageConfiguration._AVERAGE, imageConfiguration._MEDIAN, imageConfiguration._MAX, imageConfiguration._MIN};
    public String[] conv_method_string = new String[] {"Average", "Median", "Max", "Min"};
    public int[] conv_paddOpt_int = new int[]{imageConfiguration._BLACK, imageConfiguration._WHITE, imageConfiguration._ORIGINAL};
    public String[] conv_paddOpt_string = new String[]{"Black", "White", "Original"};
    
    public main_view() {
        initComponents();
        try {
            this.image = this.imageConv.conv_StringPathToBufferedImage(this.path_string);
            ImageIcon temp = this.imageConv.conv_BufferedImageToImageIcon(this.image);
            this.original_image.setIcon(temp);
            this.convolved_image.setIcon(temp);
        } catch (IOException ex) {
            Logger.getLogger(main_view.class.getName()).log(Level.SEVERE, null, ex);
        }
//        this.init_kernels();
        this.init_combobox();
    }
    private void init_kernels() {
        
    }
    private void init_combobox() {
        this.cbox_kernels.removeAllItems();
        for(byte i = 0; i < this.conv_size_string.length; i++) {
            this.cbox_kernels.addItem(this.conv_size_string[i]);
        }
        this.cbox_methods.removeAllItems();
        for(byte i = 0; i < this.conv_method_string.length; i++) {
            this.cbox_methods.addItem(this.conv_method_string[i]);
        }
        this.cbox_padd_opt.removeAllItems();
        for(byte i = 0; i < this.conv_paddOpt_string.length; i++) {
            this.cbox_padd_opt.addItem(this.conv_paddOpt_string[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        convolved_image = new javax.swing.JLabel();
        original_image = new javax.swing.JLabel();
        panel_controller = new javax.swing.JPanel();
        lbl_controller = new javax.swing.JLabel();
        cbox_kernels = new javax.swing.JComboBox();
        lbl_kernels = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_file_path = new javax.swing.JTextField();
        bt_browse = new javax.swing.JButton();
        bt_run = new javax.swing.JButton();
        cbox_methods = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        check_rgb = new javax.swing.JCheckBox();
        cbox_padd_opt = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        convolved_image.setText("convolved_image");

        original_image.setText("original_image");

        lbl_controller.setText("Controller");

        cbox_kernels.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_kernels.setText("Kernel size");

        jLabel1.setText("Input Image");

        bt_browse.setText("Browse");
        bt_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_browseActionPerformed(evt);
            }
        });

        bt_run.setText("Run");
        bt_run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_runActionPerformed(evt);
            }
        });

        cbox_methods.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Method");

        check_rgb.setText("RGB");

        cbox_padd_opt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Padding option");

        javax.swing.GroupLayout panel_controllerLayout = new javax.swing.GroupLayout(panel_controller);
        panel_controller.setLayout(panel_controllerLayout);
        panel_controllerLayout.setHorizontalGroup(
            panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_controllerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_controllerLayout.createSequentialGroup()
                        .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_controllerLayout.createSequentialGroup()
                                .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbox_kernels, 0, 171, Short.MAX_VALUE)
                                    .addComponent(tf_file_path)
                                    .addComponent(cbox_padd_opt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panel_controllerLayout.createSequentialGroup()
                                        .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_controller)
                                            .addComponent(lbl_kernels)
                                            .addComponent(jLabel1))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_browse)
                                    .addComponent(check_rgb)
                                    .addComponent(bt_run)))
                            .addComponent(cbox_methods, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20))
                    .addGroup(panel_controllerLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_controllerLayout.setVerticalGroup(
            panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_controllerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_controller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_file_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_browse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_kernels)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_kernels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_rgb))
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbox_methods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_run)
                    .addComponent(cbox_padd_opt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_controller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(original_image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(convolved_image)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(convolved_image)
                        .addComponent(original_image))
                    .addComponent(panel_controller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_browseActionPerformed
        //System.out.print(nama);
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Image File (*.jpg)", "jpg"));
        chooser.setAcceptAllFileFilterUsed(true);
        int result = chooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
//            File[] selectedImage = chooser.getSelectedFiles();
            this.path_string = chooser.getSelectedFile().getAbsolutePath();
            this.tf_file_path.setText(this.path_string);
//            this.images_path = selectedImage[0];
        }
        try {
            this.image = this.imageConv.conv_StringPathToBufferedImage(this.path_string);
            ImageIcon temp = this.imageConv.conv_BufferedImageToImageIcon(this.image);
            this.original_image.setIcon(temp);
            this.convolved_image.setIcon(temp);
//            image = ImageIO.read(this.images_path);
//            this.original_image = new JLabel(new ImageIcon(image));
        } catch (IOException ex) {
            Logger.getLogger(main_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bt_browseActionPerformed
    
    private void load_configuration () {
        this.conv_method_set = this.conv_method_int[this.cbox_methods.getSelectedIndex()];
        this.conv_paddOpt_set = this.conv_paddOpt_int[this.cbox_padd_opt.getSelectedIndex()];
        this.conv_size_set = this.conv_size_int[this.cbox_kernels.getSelectedIndex()];
        if(this.check_rgb.isSelected()) {
            this.rgb_enabled = true;
        }else {
            this.rgb_enabled = false;
        }
        this.ip.padd_opt = this.conv_paddOpt_set;
    }
    
    private void bt_runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_runActionPerformed
        this.load_configuration();
        if(this.rgb_enabled) {
            ArrayList<ArrayList<ArrayList<Double>>> display_image = ip.getPixelArrayListRGB(this.image);
            display_image = ip.ConvolveRGB(display_image, this.conv_size_set, this.conv_method_set);
            BufferedImage image_after = ip.convertMatToBMRGB(display_image);
            ImageIcon temp = new ImageIcon(image_after);
            this.convolved_image.setIcon(temp);
        }else {
            ArrayList<ArrayList<Double>> display_image = ip.getPixelArrayList(this.image);
            display_image = ip.Convolve(display_image, this.conv_size_set, this.conv_method_set);
            BufferedImage image_after = ip.convertMatToBM(display_image);
            ImageIcon temp = new ImageIcon(image_after);
            this.convolved_image.setIcon(temp);
        }
    }//GEN-LAST:event_bt_runActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_browse;
    private javax.swing.JButton bt_run;
    private javax.swing.JComboBox cbox_kernels;
    private javax.swing.JComboBox cbox_methods;
    private javax.swing.JComboBox cbox_padd_opt;
    private javax.swing.JCheckBox check_rgb;
    private javax.swing.JLabel convolved_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_controller;
    private javax.swing.JLabel lbl_kernels;
    private javax.swing.JLabel original_image;
    private javax.swing.JPanel panel_controller;
    private javax.swing.JTextField tf_file_path;
    // End of variables declaration//GEN-END:variables
}
